version: "3"

services: 
    bizbot:
        build: BusinessBot/
        ports:
            - 4444
    selenium-standalone:
        image: selenium/standalone-chrome
        ports:
            - 4444:4444